### ISSUE TITLE
Webmentions

### ISSUE THREAD

**Issue by BryanSchuetz** [miklb/jekyll-indieweb#1]
Have you considered including web mentions for a post when the site builds—rather than adding them in on the client-side?

**Comment by voxpelli** [comment]
I'm "solving" this in my theme by using an as of yet experimental embed of webmentions that progressively enhances a `u-responses` link into a list of embeds. Eg. a link like:

```html
<a class="u-responses" href="https://webmention.herokuapp.com/api/mentions?format=html&url=http%3A%2F%2Fvoxpelli.com%2F2016%2F03%2Fexperts-dont-change-the-world%2F">See mentions of this post</a>
```

That makes the mentions curlable and as long as they are curlable I don't have much issue with using a client side embed. (It's still experimental as curlable only became an issue when Salmentions became a thing as Salmentions has a need to parse mentions).

**Comment by miklb** [comment]
@BryanSchuetz my personal jekyll install does that, but requires a plugin. My goal with this project was to provide a starting point for users on GitHub pages, which doesn't support plugins (without a more complicated build/deploy process).

 You can check my personal repo in the jekyll branch to see what I'm using and feel free to ping me in IRC or the repo or Twitter if you have any questions.

**Comment by miklb** [comment]
Closing this as I believe the Jekyll Webmention plugin now properly sends Webmentions, there is no native way to do this currenty with a GitHub Pages site.
