### ISSUE TITLE
Switch to Bulma CSS Framework

### ISSUE THREAD

**Issue by miklb** [miklb/jekyll-indieweb#12]
I have become enamored with the [Bulma](http://bulma.io) framework, basically a lighter version of Bootstrap w/ an aesthetic  that fits my eye.

What are your thoughts @herestomwiththeweather ? I would keep the same basic layout. Would give a little more flexibility in design options without having to do a lot with the Liquid syntax, and a better responsive design.

**Comment by herestomwiththeweather** [comment]
better responsive design seems like it's worth it.  sounds good to me.

**Comment by miklb** [comment]
Cool. I'll start working on a 2.0 milestone and will look to formally bundle the theme as a gem for that release. I've already got the repo set up for it, just short circuited when I switched to WordPress for my main site.

**Comment by miklb** [comment]
Made surprisingly a lot of progress on this. Beauty of having clean HTML and an easy to use CSS framework.

You can see progress in the [development branch](https://github.com/miklb/jekyll-indieweb/tree/develop)

**Comment by miklb** [comment]
I've decided against using Bulma. the goal now is as light weight but aesthetic by default, with room for simple customization. It will also be a formal Jekyll gem theme.

**Comment by jonszcz** [comment]
I'm not sure if this is related, but I did just fork the repository and am getting an error on the @import within the main.scss file. If I comment out that import, the page will build properly, but looks pretty terrible. Any thoughts of what I'm missing?

**Comment by miklb** [comment]
I screwed up a merge if you are using master. I’ll see what I can do to walk it back to a point that’s where things were in another branch. My apologies.

**Comment by jonszcz** [comment]
Not a problem, I'm pretty new to all of this so I thought I was missing something.

**Comment by miklb** [comment]
you should be able to `git checkout 0.2.1` and be on the tag of the last proper release and everything should work as it did.

**Comment by jonszcz** [comment]
Perfect. I was able to get that to work this morning. Thanks so much for looking in to it. I very much appreciate it.
