### ISSUE TITLE
Reassess site config and gh-pages for urls

### ISSUE THREAD

**Issue by miklb** [miklb/jekyll-indieweb#29]
At some point there was an issue with GitHub pages hosted sites and local development that required the use of `site.github.url`

The question is – is that still necessary?

**Comment by miklb** [comment]
I'm removing all reference to `site.github.url` and using `site.baseurl`. I'm still not 100% sure on the best config, leaving open.

**Comment by infominer33** [comment]
From [August 2018](https://github.com/carpentries/styles/commit/b84e6ac5b787b831c496780d14bcc73242d8e172):

>When rendering websites locally, `site.github.url` doesn't get resolved
properly unless GitHub PAT are set up and available in the environment.
This leads to warnings and errors when trying to serve the site locally.
To work around this, we use the `jekyll.environment` variable which is set to
`development` when rendering the site locally, and set to `production` on
GitHub where `site.github.url` will be defined.

**Comment by miklb** [comment]
There is also a new feature coming in 4.0 that will make it easier to load assets. Going to close this and if any `site.github.url` are still around I'll fix/remove. Thanks @infominer33 for the research.
